<?php

namespace Etd\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository {

    public function parcinq($first) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
                ->from('EtdEtudiantBundle:Personne', 'p');
        //$qb->where(($qb->expr()->eq('d.supprimer', $qb->expr()->literal(false))));
        $qb->orderBy('p.nom', 'ASC')->setFirstResult($first)->setMaxResults(5);

        return $qb->getQuery()->getResult();
    }

    public function getProByCne($cne) {
        $cne = trim($cne);
        $cne = preg_replace('/\s+/', ' ', $cne);
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
                ->from('EtdEtudiantBundle:Personne', 'p');
        $qb->where(($qb->expr()->lower('p.cne') . 'LIKE :param'));
        $qb->setParameter('param', strtolower($cne));
        return $qb->getQuery()->getResult();
    }

    public function Chercherpersonne($valeurcherchee) {
        $tab = explode('/', $valeurcherchee);
        if (count($tab) >= 1) {
            $tab = array_reverse($tab);
            $SearchVal1 = implode('-', $tab);
        }
        $qb = $this->_em->createQueryBuilder();
        $qb->select('d')
                ->from('EtdEtudiantBundle:Personne', 'd');
        $qb->where(($qb->expr()->lower('d.prenom') . 'LIKE :val'))
                ->orwhere(($qb->expr()->lower('d.nom') . 'LIKE :val'))
                ->orwhere(($qb->expr()->lower('d.fonction') . 'LIKE :val'));
               // ->andWhere($qb->expr()->eq('d.supprimer', $qb->expr()->literal(false)));

        $qb->setParameter('val', '%' . strtolower($SearchVal1) . '%')
                ->orderBy('d.nom', 'ASC');
        return $qb->getQuery()->getResult();
    }

}
