<?php

namespace Etd\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotopersonneRepository extends EntityRepository
{
}
