<?php

namespace Etd\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends EntityRepository
{
     public function parcinq($first) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('v')
                ->from('EtdEtudiantBundle:Voiture', 'v');
        //$qb->where(($qb->expr()->eq('d.supprimer', $qb->expr()->literal(false))));
        $qb->orderBy('v.marque', 'ASC')->setFirstResult($first)->setMaxResults(5);

        return $qb->getQuery()->getResult();
    }
}
